name: Report a Bug
description: Report a Bug.
labels: ['unconfirmed bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please take time to fill out the information below.
  - type: dropdown
    attributes:
      label: Bug Type
      description: What type of bug are you trying to report?
      multiple: true
      options:
        - Performance
        - Memory Leak / SEGFAULT
        - Compatibility Issues
        - Console Errors
        - Inaccurate Documentation
        - Other Unexpected Behavior
    validations:
      required: true

  - type: input
    attributes:
      label: Project Version
      description: What version of the project are you using?
      placeholder: |
        Ex: "1.0.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Give us a description of what is going on and what you expect to happen.
      placeholder: |
        Ex: "Coordinate not being added correctly"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What is actually going on?
      placeholder: |
        Ex: "Coordinate3D is added instead of Coordinate2D"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        In the box below, you can attach any relevant info or files that may help us solve the bug.
        If you think this issue is relevant to any other issues, please mention it here.
  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information that may help us solve the bug.
      placeholder: |
        Ex: "Running on Debian"
    validations:
      required: false
